require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c",
		"diff",
		"dockerfile",
		"elixir",
		"fish",
		"git_config",
		"git_rebase",
		"gitcommit",
		"gitignore",
		"html",
		"http",
		"java",
		"json",
		"lua",
		"make",
		"markdown",
		"markdown_inline",
		"python",
		"query",
		"rust",
		"sql",
		"ssh_config",
		"toml",
		"vim",
		"vimdoc",
		"yaml",
	},
	auto_install = true,
	sync_install = false,
	highlight = { enable = true, disable = { "tmux" } },
	indent = { enable = true },
})
